---

- name: ZOOKEEPER | Removing dependencies
  apt:
    pkg: "zookeeper"
    state: absent

- name: ZOOKEEPER | Installing dependencies
  apt:
    name: "{{ zookeeper_required_libs }}"
    state: present

- name: ZOOKEEPER | Ensure ZooKeeper group
  group:
    name: "{{ zookeeper_group }}"
    system: true

- name: ZOOKEEPER | Ensure ZooKeeper user
  user:
    name: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    shell: /bin/false
    system: true
    create_home: false

- name: ZOOKEEPER | Create install path
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: 0755
  loop:
    - "{{ zookeeper_install_path }}"
    - "{{ zookeeper_conf_dir }}"
    - "{{ zookeeper_data_dir }}"
    - "{{ zookeeper_data_log_dir }}"
    - "{{ zookeeper_log_dir }}"

- name: ZOOKEEPER | Check ZooKeeper version
  shell: |
    set -o pipefail && \
    echo status | nc localhost {{ zookeeper_client_port }}
  register: zookeeper_check
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false

- name: ZOOKEEPER | Untar ZooKeeper
  unarchive:
    extra_opts: ['--strip-components=1']
    src: "{{ zookeeper_url }}"
    remote_src: true
    dest: "{{ zookeeper_install_path }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  when: "zookeeper_force_reinstall or zookeeper_check is failed or zookeeper_version not in zookeeper_check.stdout"

- name: ZOOKEEPER | Remove upstart service
  file:
    path: /etc/init.d/zookeeper
    state: absent
