---

- name: ZOOKEEPER | Install
  import_tasks: install.yml
  tags:
    - zookeeper_install

- name: ZOOKEEPER | Agent config
  import_tasks: agent.yml
  tags:
    - kafka_agents_config
  when: zookeeper_agents_config is defined

- name: ZOOKEEPER | Config
  import_tasks: config.yml
  tags:
    - zookeeper_config

- name: ZOOKEEPER | Service
  import_tasks: service.yml
  tags:
    - zookeeper_service

- name: ZOOKEEPER | Check zookeepers cluster status
  shell: |
    set -o pipefail && \
    echo stat | nc 127.0.0.1 2181 | grep Mode | grep -E -w  "leader|follower"
