---

- name: ZOOKEEPER | Configuring ZooKeeper service
  systemd:
    name: zookeeper
    state: "{{ zookeeper_service_state }}"
    enabled: "{{ zookeeper_service_enabled }}"
    daemon_reload: true
  register: zookeeper_service_output