---

zookeeper_hosts:
  - host: zookeeper1
    ip: "{{ (ansible_hostname == 'zookeeper1') | ternary('0.0.0.0', 'zookeeper1') }}"
    id: 1
  - host: zookeeper2
    ip: "{{ (ansible_hostname == 'zookeeper2') | ternary('0.0.0.0', 'zookeeper2') }}"
    id: 2
  - host: zookeeper3
    ip: "{{ (ansible_hostname == 'zookeeper3') | ternary('0.0.0.0', 'zookeeper3') }}"
    id: 3

zookeeper_config_map:
  - key: traceFile
    value: zoo-trace.log
