---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Build Docker Image
      docker_image:
        path: "."
        name: "idealista/zookeeper"

    - name: Create Docker container
      docker_container:
        name: "zookeeper"
        hostname: "zookeeper"
        image: "idealista/zookeeper"
        privileged: true

    - name: Add container to in-memory inventory
      add_host:
        name: "zookeeper"
        ansible_connection: docker

# Due an Ansible Bug it's not possible to execute this task using "delegate_to" in play defined before
# because was launched using "connection: local" :(
- name: Execute Zookeeper role in Docker container
  hosts: zookeeper
  roles:
    - zookeeper_role

- name: Deploy to Docker Hub
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Commit container file changes to new image
      command: docker commit \
        zookeeper idealista/zookeeper

    - name: Log into Docker Hub
      docker_login:
        email: "{{ docker_hub_email }}"
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Tag and push to Docker Hub
      command: docker push idealista/zookeeper:latest

    - name: Remove the container
      docker_container:
        name: "zookeeper"
        state: absent
